In [7]:
import pandas as pd
df=pd.read_csv('Cleaned_data.csv')

In [8]:
df

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,17.0,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.0,2996.0,2996.0,333.0,63.75
1,Nissan Magnite,21.0,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.0,999.0,999.0,9863.0,8.99
2,BMW X1,18.0,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.0,1995.0,1995.0,188.0,23.75
3,Kia Seltos,19.0,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.0,1353.0,1353.0,13808.0,13.56
4,Skoda Superb,19.0,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.0,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,Hyundai Creta,20.0,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.0,11345.0,11345.0,250.0,17.41
1549,Renault KWID,NaN,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999.0,6706.0,6706.0,91.0,3.98
1550,Honda WR-V,17.0,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.0,1199.0,1199.0,887.0,5.85
1551,Volkswagen Polo,18.0,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.0,999.0,999.0,75.0,4.75
1552,Maruti Swift,18.0,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.0,1197.0,1197.0,8314.0,6.10

In [9]:
df.drop("Unnamed: 0",axis=1,inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
df

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,17.0,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.0,2996.0,2996.0,333.0,63.75
1,Nissan Magnite,21.0,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.0,999.0,999.0,9863.0,8.99
2,BMW X1,18.0,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.0,1995.0,1995.0,188.0,23.75
3,Kia Seltos,19.0,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.0,1353.0,1353.0,13808.0,13.56
4,Skoda Superb,19.0,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.0,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,Hyundai Creta,20.0,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.0,11345.0,11345.0,250.0,17.41
1549,Renault KWID,NaN,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999.0,6706.0,6706.0,91.0,3.98
1550,Honda WR-V,17.0,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.0,1199.0,1199.0,887.0,5.85
1551,Volkswagen Polo,18.0,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.0,999.0,999.0,75.0,4.75
1552,Maruti Swift,18.0,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.0,1197.0,1197.0,8314.0,6.10

# Handling missing values

In [ ]:
df.isnull().sum()

car_name                0
registration_year     145
insurance_validity      0
fuel_type               0
seats                   0
kms_driven              0
ownsership              0
transmission            0
manufacturing_year      0
mileage(kmpl)           3
engine(cc)              3
max_power(bhp)          3
torque(Nm)              4
price(in lakhs)         0
dtype: int64

In [10]:
df['mileage(kmpl)'].unique()

array([   7.,   17.,   20.,   16.,   14.,   18.,   15.,   13.,   21.,
         22.,   12.,  998.,   26., 1498.,   10.,   11.,   19., 2179.,
       2993., 1950.,   25., 2755., 1197., 1086., 1997., 2996., 1999.,
       1461., 1196., 1969.,   23., 1995., 1451.,   27., 1998., 1493.,
        999., 1984.,    9., 1497.,   24., 1996., 1991., 2925.,  796.,
        147.,    8.,   nan, 2999.,   28.,  285., 2987., 1396.,  814.,
        624., 1198., 1495., 1199., 2198., 1248., 1120., 2995., 3996.,
        245., 1061., 1968.])

In [ ]:
# df['mileage(kmpl)'] = df['mileage(kmpl)'].astype(str)

# df['mileage(kmpl)'] = df['mileage(kmpl)'].str.extract(r'(\d+\.?\d*)')

# df['mileage(kmpl)'] = pd.to_numeric(df['mileage(kmpl)'], errors='coerce')

In [ ]:
df['mileage(kmpl)'] = df['mileage(kmpl)'].fillna(df['mileage(kmpl)'].median())
df['engine(cc)'] = df['engine(cc)'].fillna(df['engine(cc)'].median())
df['max_power(bhp)'] = df['max_power(bhp)'].fillna(df['max_power(bhp)'].median())
df['torque(Nm)'] = df['torque(Nm)'].fillna(df['torque(Nm)'].median())

## replacing the null values of registration_year with manufacturing_year
df['registration_year'] = df['registration_year'].fillna(df['manufacturing_year'])

In [ ]:
df['mileage(kmpl)']

0          7.0
1         17.0
2         20.0
3         16.0
4         14.0
         ...
1548    1493.0
1549     999.0
1550      17.0
1551      18.0
1552      20.0
Name: mileage(kmpl), Length: 1553, dtype: float64

In [ ]:
df.isnull().sum()

car_name              0
registration_year     0
insurance_validity    0
fuel_type             0
seats                 0
kms_driven            0
ownsership            0
transmission          0
manufacturing_year    0
mileage(kmpl)         0
engine(cc)            0
max_power(bhp)        0
torque(Nm)            0
price(in lakhs)       0
dtype: int64

In [11]:
df

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,17.0,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.0,2996.0,2996.0,333.0,63.75
1,Nissan Magnite,21.0,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.0,999.0,999.0,9863.0,8.99
2,BMW X1,18.0,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.0,1995.0,1995.0,188.0,23.75
3,Kia Seltos,19.0,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.0,1353.0,1353.0,13808.0,13.56
4,Skoda Superb,19.0,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.0,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,Hyundai Creta,20.0,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.0,11345.0,11345.0,250.0,17.41
1549,Renault KWID,NaN,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999.0,6706.0,6706.0,91.0,3.98
1550,Honda WR-V,17.0,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.0,1199.0,1199.0,887.0,5.85
1551,Volkswagen Polo,18.0,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.0,999.0,999.0,75.0,4.75
1552,Maruti Swift,18.0,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.0,1197.0,1197.0,8314.0,6.10

In [12]:
df.to_csv("final_data.csv",index=False)