In [48]:
import pandas as pd
df=pd.read_csv("Used Car Dataset.csv")
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [23]:
df.reset_index(drop=True)
df.drop('Unnamed: 0', axis=1)

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class S400,NaN,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7,2996,2996.0,333.0,63.75
1,Nissan Magnite Turbo CVT XV Premium Opt BSVI,NaN,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17,999,999.0,9863.0,8.99
2,BMW X1 sDrive 20d xLine,NaN,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20,1995,1995.0,188.0,23.75
3,Kia Seltos GTX Plus,NaN,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16,1353,1353.0,13808.0,13.56
4,Skoda Superb LK 1.8 TSI AT,NaN,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14,1798,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,Hyundai Creta SX Opt Diesel AT BSVI,NaN,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493,11345,11345.0,250.0,17.41
1549,Renault KWID 1.0 RXL Opt BSVI,NaN,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999,6706,6706.0,91.0,3.98
1550,Honda WR-V i-VTEC S,NaN,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17,1199,1199.0,887.0,5.85
1551,Volkswagen Polo 1.0 MPI Comfortline,NaN,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18,999,999.0,75.0,4.75
1552,Maruti Swift Dzire VXI,NaN,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20,1197,1197.0,8314.0,6.10

In [21]:
df.dtypes

Unnamed: 0              int64
car_name               object
registration_year     float64
insurance_validity     object
fuel_type              object
seats                   int64
kms_driven              int64
ownsership             object
transmission           object
manufacturing_year     object
mileage(kmpl)         float64
engine(cc)             object
max_power(bhp)        float64
torque(Nm)            float64
price(in lakhs)       float64
dtype: object

In [ ]:
df['car_name']=df['car_name'].str.replace(r'^\d{4}\s*','',regex=True)
df['registration_year'] = df['registration_year'].astype(str)
df['registration_year']=df['registration_year'].str.split('-').str[1]   ## here 17 means 2017, 20 means 2020 etc
df['engine(cc)'] = df['engine(cc)'].astype(str)
df['engine(cc)']=df['engine(cc)'].str.split('.').str[0]
df['mileage(kmpl)'] = df['mileage(kmpl)'].astype(str)
df['mileage(kmpl)']=df['mileage(kmpl)'].str.split('.').str[0]

df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,Mercedes-Benz S-Class S400,17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7,2996,2996.0,333.0,63.75
1,1,Nissan Magnite Turbo CVT XV Premium Opt BSVI,21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17,999,999.0,9863.0,8.99
2,2,BMW X1 sDrive 20d xLine,18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20,1995,1995.0,188.0,23.75
3,3,Kia Seltos GTX Plus,19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16,1353,1353.0,13808.0,13.56
4,4,Skoda Superb LK 1.8 TSI AT,19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14,1798,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,1548,Hyundai Creta SX Opt Diesel AT BSVI,20,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493,11345,11345.0,250.0,17.41
1549,1549,Renault KWID 1.0 RXL Opt BSVI,NaN,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999,6706,6706.0,91.0,3.98
1550,1550,Honda WR-V i-VTEC S,17,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17,1199,1199.0,887.0,5.85
1551,1551,Volkswagen Polo 1.0 MPI Comfortline,18,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18,999,999.0,75.0,4.75
1552,1552,Maruti Swift Dzire VXI,18,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20,1197,1197.0,8314.0,6.10

In [11]:
df['kms_driven'].unique

<bound method Series.unique of 0       56000
1       30615
2       24000
3       18378
4       44900
        ...
1548    35000
1549    10000
1550    49000
1551    40000
1552    34756
Name: kms_driven, Length: 1553, dtype: int64>

In [50]:
df.reset_index(drop=True, inplace=True)

df.drop('Unnamed: 0', axis=1, inplace=True, errors='ignore')

df.head()

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class S400,17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7,2996,2996.0,333.0,63.75
1,Nissan Magnite Turbo CVT XV Premium Opt BSVI,21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17,999,999.0,9863.0,8.99
2,BMW X1 sDrive 20d xLine,18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20,1995,1995.0,188.0,23.75
3,Kia Seltos GTX Plus,19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16,1353,1353.0,13808.0,13.56
4,Skoda Superb LK 1.8 TSI AT,19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14,1798,1798.0,17746.0,24.00

In [51]:
## taking 1st 2 string from car_name column
df['car_name']=df['car_name'].str.split().str[0:2].str.join(' ')
df.head()

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7,2996,2996.0,333.0,63.75
1,Nissan Magnite,21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17,999,999.0,9863.0,8.99
2,BMW X1,18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20,1995,1995.0,188.0,23.75
3,Kia Seltos,19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16,1353,1353.0,13808.0,13.56
4,Skoda Superb,19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14,1798,1798.0,17746.0,24.00

In [53]:
df.to_csv("Cleaned_data.csv")